trie.lo: /home/vagrant/Code/php_source_code/php-5.4.18/ext/trie/trie.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vagrant/Code/php_source_code/php-5.4.18/ext/trie $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vagrant/Code/php_source_code/php-5.4.18/ext/trie/trie.c -o trie.lo 
$(phplibdir)/trie.la: ./trie.la
	$(LIBTOOL) --mode=install cp ./trie.la $(phplibdir)

./trie.la: $(shared_objects_trie) $(TRIE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_trie) $(TRIE_SHARED_LIBADD)

